### ISSUE TITLE
Release 0.3.1

### ISSUE THREAD

**Issue by at-wat** [at-wat/neonavigation#238]
remaining works:
- [x] #229 #244 trajectory_tracker: path following for path nodes containing velocity field
- [x] #249 trajectory_tracker: add acceleration factor parameter of time optimal control
- [x] #250 trajectory_tracker: fix robot pose prediction
- [x] #251 trajectory_tracker: fix local goal handling
- [x] #252 trajectory_tracker: fix angular velocity limit
- [x] #256 Add neonavigation_launch to trajectory_tracker_rviz_plugins dependency

**Comment by at-wat** [comment]
To sync version with msgs, next release version will be 0.3.1, skipping 0.3.0.

**Comment by at-wat** [comment]
bloom release:
- [ ] I
- [ ] K
- [ ] L
- [ ] M (new)

post-release test:
- [ ] I
- [ ] K
- [ ] L
- [ ] M
